.TH "include/collector.hpp" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/collector.hpp \- Final Project - ecobot (A trash Collecting Robot)  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Final Project - ecobot (A trash Collecting Robot) 


.PP
\fBCopyright:\fP
.RS 4
BSD 3-Clause License 
.PP
Copyright © 2019 Raj Shinde, Prasheel Renkuntla
.RE
.PP
\fBAuthor:\fP
.RS 4
Prasheel Renkuntla 
.PP
Raj Shinde 
.RE
.PP
\fBDate:\fP
.RS 4
12/09/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
.SH "file for collecting trash"
.PP

.PP
Definition in file \fBcollector\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
