.TH "GridSquare" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridSquare \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gridSquare\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridSquare\fP ()"
.br
.RI "\fIConstructor of class \fBGridSquare\fP\&. \fP"
.ti -1c
.RI "\fB~GridSquare\fP ()"
.br
.RI "\fIDestructor of class \fBGridSquare\fP\&. \fP"
.ti -1c
.RI "int \fBgetCurrentGridSquare\fP ()"
.br
.RI "\fIFunction fo get current grid square\&. \fP"
.ti -1c
.RI "float \fBgetFCost\fP ()"
.br
.RI "\fIFunction to get current function Cost\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrentGridSquare\fP"
.br
.ti -1c
.RI "float \fBfCost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file gridSquare\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GridSquare::GridSquare ()"

.PP
Constructor of class \fBGridSquare\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 57 of file gridSquare\&.cpp\&.
.SS "GridSquare::~GridSquare ()"

.PP
Destructor of class \fBGridSquare\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 62 of file gridSquare\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int GridSquare::getCurrentGridSquare ()"

.PP
Function fo get current grid square\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int, current grid square 
.RE
.PP

.PP
Definition at line 67 of file gridSquare\&.cpp\&.
.SS "float GridSquare::getFCost ()"

.PP
Function to get current function Cost\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
float, current F cost 
.RE
.PP

.PP
Definition at line 71 of file gridSquare\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int GridSquare::currentGridSquare"

.PP
Definition at line 57 of file gridSquare\&.hpp\&.
.SS "float GridSquare::fCost"

.PP
Definition at line 58 of file gridSquare\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
