.TH "test/main.cpp" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBthreadSpinning\fP (void)"
.br
.RI "\fIMain Function for running tests\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 64 of file main\&.cpp\&.
.SS "void threadSpinning (void)"

.PP
Main Function for running tests\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP argc, char argv 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 55 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
