.TH "Randomizer" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Randomizer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <randomizer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomizer\fP ()"
.br
.RI "\fIConstructor of class \fBRandomizer\fP\&. \fP"
.ti -1c
.RI "\fB~Randomizer\fP ()"
.br
.RI "\fIDestructor of class \fBRandomizer\fP\&. \fP"
.ti -1c
.RI "double \fBrandomizeX\fP ()"
.br
.RI "\fIfunction to randomize x \fP"
.ti -1c
.RI "double \fBrandomizeY\fP ()"
.br
.RI "\fIfunction to randomize y \fP"
.ti -1c
.RI "double \fBxOffset\fP (double xo, double xr, double xn)"
.br
.RI "\fIfunction to offset x \fP"
.ti -1c
.RI "double \fByOffset\fP (double yo, double yr, double yn)"
.br
.RI "\fIfunction to offset y \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBxc\fP"
.br
.ti -1c
.RI "double \fByc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file randomizer\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Randomizer::Randomizer ()"

.PP
Constructor of class \fBRandomizer\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 50 of file randomizer\&.cpp\&.
.SS "Randomizer::~Randomizer ()"

.PP
Destructor of class \fBRandomizer\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 53 of file randomizer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "double Randomizer::randomizeX ()"

.PP
function to randomize x 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double xr 
.RE
.PP

.PP
Definition at line 56 of file randomizer\&.cpp\&.
.SS "double Randomizer::randomizeY ()"

.PP
function to randomize y 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
double yr 
.RE
.PP

.PP
Definition at line 69 of file randomizer\&.cpp\&.
.SS "double Randomizer::xOffset (double xo, double xr, double xn)"

.PP
function to offset x 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP xo, robot origin 
.br
\fIdouble\fP xr, trash 
.br
\fIdouble\fP xn, target 
.RE
.PP
\fBReturns:\fP
.RS 4
double xn, new traget 
.RE
.PP

.PP
Definition at line 81 of file randomizer\&.cpp\&.
.SS "double Randomizer::yOffset (double yo, double yr, double yn)"

.PP
function to offset y 
.PP
\fBParameters:\fP
.RS 4
\fIdouble\fP yo, robot origin 
.br
\fIdouble\fP yr, trash 
.br
\fIdouble\fP yn, traget 
.RE
.PP
\fBReturns:\fP
.RS 4
double yn, new target 
.RE
.PP

.PP
Definition at line 86 of file randomizer\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "double Randomizer::xc"

.PP
Definition at line 51 of file randomizer\&.hpp\&.
.SS "double Randomizer::yc"

.PP
Definition at line 51 of file randomizer\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
