.TH "SpawnCollect" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpawnCollect \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spawnCollect\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpawnCollect\fP ()"
.br
.RI "\fIConstructor of class \fBSpawnCollect\fP\&. \fP"
.ti -1c
.RI "\fB~SpawnCollect\fP ()"
.br
.RI "\fIConstructor of class \fBSpawnCollect\fP\&. \fP"
.ti -1c
.RI "bool \fBspawn\fP (int xr, int yr, int flag)"
.br
.RI "\fIFunction to spawn trash\&. \fP"
.ti -1c
.RI "bool \fBcollect\fP (int flag)"
.br
.RI "\fIFunction to collect trash\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBxc\fP"
.br
.ti -1c
.RI "int \fByc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file spawnCollect\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpawnCollect::SpawnCollect ()"

.PP
Constructor of class \fBSpawnCollect\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 50 of file spawnCollect\&.cpp\&.
.SS "SpawnCollect::~SpawnCollect ()"

.PP
Constructor of class \fBSpawnCollect\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fInone\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
none 
.RE
.PP

.PP
Definition at line 53 of file spawnCollect\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SpawnCollect::collect (int flag)"

.PP
Function to collect trash\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP flag, reference 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 68 of file spawnCollect\&.cpp\&.
.SS "bool SpawnCollect::spawn (int xr, int yr, int flag)"

.PP
Function to spawn trash\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP xr, trash x location 
.br
\fIint\fP yr, trash y cocation 
.br
\fIint\fP flag, reference 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 56 of file spawnCollect\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int SpawnCollect::xc"

.PP
Definition at line 51 of file spawnCollect\&.hpp\&.
.SS "int SpawnCollect::yc"

.PP
Definition at line 51 of file spawnCollect\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
