.TH "test/testRandomizer.cpp" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/testRandomizer.cpp \- Final Project - ecobot (A trash Collecting Robot)  

.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'randomizer\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (testRandomizer, checkRange)"
.br
.ti -1c
.RI "\fBTEST\fP (testRandomizer, checkOffset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Final Project - ecobot (A trash Collecting Robot) 


.PP
\fBCopyright:\fP
.RS 4
BSD 3-Clause License 
.PP
Copyright © 2019 Raj Shinde, Prasheel Renkuntla
.RE
.PP
\fBAuthor:\fP
.RS 4
Prasheel Renkuntla 
.PP
Raj Shinde 
.RE
.PP
\fBDate:\fP
.RS 4
12/09/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
.SH "cases for pathPlanner Algorithm"
.PP

.PP
Definition in file \fBtestRandomizer\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "TEST (testRandomizer, checkRange)"

.PP
Definition at line 54 of file testRandomizer\&.cpp\&.
.SS "TEST (testRandomizer, checkOffset)"

.PP
Definition at line 65 of file testRandomizer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
