.TH "test/testSpawnCollect.cpp" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/testSpawnCollect.cpp \- Final Project - ecobot (A trash Collecting Robot)  

.SH SYNOPSIS
.br
.PP
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'spawnCollect\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (testspawnCollect, checkSpawn)"
.br
.ti -1c
.RI "\fBTEST\fP (testspawnCollect, checkCollect)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fIMain Function for running tests\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Final Project - ecobot (A trash Collecting Robot) 


.PP
\fBCopyright:\fP
.RS 4
BSD 3-Clause License 
.PP
Copyright © 2019 Raj Shinde, Prasheel Renkuntla
.RE
.PP
\fBAuthor:\fP
.RS 4
Prasheel Renkuntla 
.PP
Raj Shinde 
.RE
.PP
\fBDate:\fP
.RS 4
12/09/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
.SH "cases for pathPlanner Algorithm"
.PP

.PP
Definition in file \fBtestSpawnCollect\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main Function for running tests\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP argc, char argv 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 75 of file testSpawnCollect\&.cpp\&.
.SS "TEST (testspawnCollect, checkSpawn)"

.PP
Definition at line 54 of file testSpawnCollect\&.cpp\&.
.SS "TEST (testspawnCollect, checkCollect)"

.PP
Definition at line 64 of file testSpawnCollect\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
