.TH "test/testNavigateRobot.cpp" 3 "Mon Dec 9 2019" "Version 3.0" "eco-bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/testNavigateRobot.cpp \- Final Project - ecobot (A trash Collecting Robot)  

.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <tf/transform_listener\&.h>\fP
.br
\fC#include <geometry_msgs/Twist\&.h>\fP
.br
\fC#include <std_msgs/Empty\&.h>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include 'navigateRobot\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (TestNavigateRobot, testTwistRobot)"
.br
.ti -1c
.RI "\fBTEST\fP (TestNavigateRobot, testStart)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fIMain Function for running tests for Navigate Robot Class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Final Project - ecobot (A trash Collecting Robot) 


.PP
\fBCopyright:\fP
.RS 4
BSD 3-Clause License 
.PP
Copyright © 2019 Raj Shinde, Prasheel Renkuntla
.RE
.PP
\fBAuthor:\fP
.RS 4
Raj Shinde 
.PP
Prasheel Renkuntla 
.RE
.PP
\fBDate:\fP
.RS 4
12/09/2019 
.RE
.PP
\fBVersion:\fP
.RS 4
3\&.0 
.RE
.PP
.SH "test grid squares of the map\&. for planner"
.PP

.PP
Definition in file \fBtestNavigateRobot\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Main Function for running tests for Navigate Robot Class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIint\fP argc, char argv 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 127 of file testNavigateRobot\&.cpp\&.
.SS "TEST (TestNavigateRobot, testTwistRobot)"

.PP
Definition at line 57 of file testNavigateRobot\&.cpp\&.
.SS "TEST (TestNavigateRobot, testStart)"

.PP
Definition at line 96 of file testNavigateRobot\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for eco-bot from the source code\&.
